
```{r}
#clear R Environment and set the seed
rm(list=ls())
set.seed(2000)
```

```{r}
#load dplyr package for data manipulation, ggplot2 for visualization, and writexl to write results into excel
library(dplyr)
library(ggplot2)
library(writexl)

#load lavaan and semTools packages to perform confirmatory factor analysis and measure composite reliability
library(lavaan)    
library(semTools)

#load robustbase and car packages to perform robust multiple linear regression
library(robustbase)
library(car)

#load nnet package to perform multinominal regression
library(nnet)

#load the ppcor package to calculate the partial spearman's rank correlation
library(ppcor)

#load the data file
data <- as.data.frame(read.csv("sim_input.csv"))
```

```{r}
#Convert coded dichotomous columns into labelled factors 
coded_cols <- c(14:19)
data[,coded_cols] <- lapply(data[,coded_cols], 
                            function(x) factor(x, levels = c(0, 1), labels = c("No", "Yes"))
                            )

#Data cleaning
cols_to_change <- c(88, 90, 91)
data[,cols_to_change] <- lapply(data[,cols_to_change], 
                                function(x) {
  x[x == "0_1"] <- "0"
  x[x == "0_2"] <- "0"
  x[x == "1_2"] <- "1"
  x[x == "2_2"] <- "2"
  return(x)
  }
  )

#Subset data based on device ID
cat("No. of responses: ", 
    nrow(data), 
    "\n"
    )
data_unique <- data[!duplicated(data$deviceid),]
cat("No. of unique responses: ", 
    nrow(data_unique), 
    "\n"
    )

#Keep responses from undergraduate students
data_under <- data_unique[data_unique$undergrad_now == "Yes", ]
cat("No. of undergraduate participants: ", 
    nrow(data_under), 
    "\n"
    )

#Exclude non-smokers
sample <- data_under[data_under$smoke_stat == "smoker" | data_under$smoke_stat == "ex_smoker", ]
cat("No. of responses following exclusion of non-smokers: ", 
    nrow(sample),
    "\n"
    )

#Keep responses from attentive participants
sample$attention <- ifelse(
   (!is.na(sample$attention_check_a) & sample$attention_check_a == 3) |
   (!is.na(sample$attention_check_b) & sample$attention_check_b == 6),
   "Yes", "No"
)
data_attentive <- sample[sample$attention == "Yes", ]
cat("No. of attentive participants: ", 
    nrow(data_attentive), 
    "\n"
    )

#Keep responses with sufficient response time
data_attentive$response_threshold <- apply(data_attentive, 
                                         1, function(row) (sum(!is.na(row))*2)-12  #12 is subtracted for ID and multiple-response variables
                                         )
data_cleaned <- data_attentive[data_attentive$response_time > data_attentive$response_threshold, ]
cat("No. of responses following exclusion based on response time: ", 
    nrow(data_cleaned),
    "\n"
    )

#Convert behavioral rating scales into factors for data summarization
scale_cols <- c(22:42, 44:99)
data_cleaned[,scale_cols] <- lapply(data_cleaned[,scale_cols], 
                                    function(x) factor(x)
                                    )

#Create a function to summarize each variable
summarize_variable <- function(var) {
  
  if (is.numeric(var)) {
    q <- quantile(var, 
                  probs = c(0.25, 0.5, 0.75), 
                  na.rm = TRUE
                  )
    return(sprintf("Median: %.1f (Q1: %.1f, Q3: %.1f)", q[2], q[1], q[3]))
    
  } else {
    tbl <- table(var)
    prop <- prop.table(tbl)
    return(paste0(
      names(tbl), ": ", as.integer(tbl), " (", round(100 * prop, 1), "%)",
      collapse = "; "
      )
      )
  }
}

#Report summary statistics
exc_var <- c(1, 3, 13)
summary_df <- data.frame(Characteristic = names(data_cleaned[,-exc_var]),
                         Distribution = sapply(data_cleaned[,-exc_var], summarize_variable),
                         row.names = NULL
                         )
summary_df
```


```{r}
#Return behavioral scales into numeric variables for analysis
data_cleaned[, scale_cols] <- lapply(data_cleaned[, scale_cols], function(x) {
  as.numeric(as.character(x))
})

#Calculate the item-item correlation matrix for the WISDM-37 and write into an excel file
wisdm37 <- setdiff(44:81, 71)
wisdm37_cor <- as.data.frame(cor(data_cleaned[,wisdm37], 
                                 method = "spearman")
                             )
write_xlsx(wisdm37_cor, 
           "WISDM-37 item-item correlation matrix.xlsx"
           )

#Calculate the item-item correlation matrix for the RFQ and write into an excel file
rfq <- setdiff(22:42, 35)
rfq_cor <- as.data.frame(cor(data_cleaned[,rfq], 
                             method = "spearman")
                         )
write_xlsx(rfq_cor, 
           "RFQ item-item correlation matrix.xlsx"
           )
```

```{r}
#Confirmatory factor analysis for the WISDM-37 questionnaire:

#Based on continuous variables:

#Model 1: 1-factor solution
cont_mod1 <-'f =~ auto1 + auto2 + auto3 + auto4 + 
                  loc1 + loc2 + loc3 + loc4 + 
                  tol1 + tol2 + tol3 + tol4 + 
                  craving1 + craving2 + craving3 + craving4 +
                  taste1 + taste2 + taste3 +
                  cog_e1 + cog_e2 + cog_e3 +
                  w_control1 + w_control2 + w_control3 +
                  cue1 + cue2 + cue3 + 
                  affect1 + affect2 + affect3 + 
                  attach1 + attach2 + attach3 +
                  social1 + social2 +social3
                  '
cont_mod1_fit <- cfa(cont_mod1, 
                     data = data_cleaned, 
                     estimator = "MLR"
                     )
summary(cont_mod1_fit, 
        standardized = TRUE, 
        fit.measures = TRUE
        )

#Model 2: 11-factor solution
cont_mod2 <-'#Primary dependence motives
             auto      =~ auto1 + auto2 + auto3 + auto4
             loc       =~ loc1 + loc2 + loc3 + loc4
             tol       =~ tol1 + tol2 + tol3 + tol4
             craving   =~ craving1 + craving2 + craving3 + craving4
             
             #Secondary dependence motives
             taste     =~ taste1 + taste2 + taste3
             cog_e     =~ cog_e1 + cog_e2 + cog_e3
             w_control =~ w_control1 + w_control2 + w_control3
             cue       =~ cue1 + cue2 + cue3
             affect    =~ affect1 + affect2 + affect3
             attach    =~ attach1 + attach2 + attach3
             social    =~ social1 + social2 +social3
             '
cont_mod2_fit <- cfa(cont_mod2, 
                     data = data_cleaned, 
                     estimator = "MLR"
                     )
summary(cont_mod2_fit, 
        standardized = TRUE, 
        fit.measures = TRUE
        )

#Model 3: 2-factor solution
cont_mod3 <- 'pdm =~ auto1 + auto2 + auto3 + auto4 + 
                     loc1 + loc2 + loc3 + loc4 + 
                     tol1 + tol2 + tol3 + tol4 + 
                     craving1 + craving2 + craving3 + craving4
                     
              sdm =~ taste1 + taste2 + taste3 +
                     cog_e1 + cog_e2 + cog_e3 +
                     w_control1 + w_control2 + w_control3 +
                     cue1 + cue2 + cue3 + 
                     affect1 + affect2 + affect3 + 
                     attach1 + attach2 + attach3 +
                     social1 + social2 +social3
                     '
cont_mod3_fit <- cfa(cont_mod3, 
                     data = data_cleaned, 
                     estimator = "MLR"
                     )
summary(cont_mod3_fit, 
        standardized = TRUE,
        fit.measures = TRUE
        )

#Model 4: 2-order solution
cont_mod4 <- '#1st order
             auto      =~ auto1 + auto2 + auto3 + auto4
             loc       =~ loc1 + loc2 + loc3 + loc4
             tol       =~ tol1 + tol2 + tol3 + tol4
             craving   =~ craving1 + craving2 + craving3 + craving4
             taste     =~ taste1 + taste2 + taste3
             cog_e     =~ cog_e1 + cog_e2 + cog_e3
             w_control =~ w_control1 + w_control2 + w_control3
             cue       =~ cue1 + cue2 + cue3
             affect    =~ affect1 + affect2 + affect3
             attach    =~ attach1 + attach2 + attach3
             social    =~ social1 + social2 +social3
             
             #2nd order
             pdm =~ auto + loc + tol + craving
             sdm =~ taste + cog_e + w_control + cue + affect + attach + social
             '
cont_mod4_fit <- cfa(cont_mod4, 
                     data = data_cleaned, 
                     estimator = "MLR"
                     )
summary(cont_mod4_fit, 
        standardized = TRUE, 
        fit.measures = TRUE
        )

#Based on ordinal variables:
items <- c("auto1", "auto2", "auto3", "auto4",
           "loc1", "loc2", "loc3", "loc4",
           "tol1", "tol2", "tol3", "tol4",
           "craving1", "craving2", "craving3", "craving4",
           "taste1", "taste2", "taste3",
           "cog_e1", "cog_e2", "cog_e3",
           "w_control1", "w_control2", "w_control3",
           "cue1", "cue2", "cue3",
           "affect1", "affect2", "affect3",
           "attach1", "attach2", "attach3",
           "social1", "social2", "social3"
           )

#Model 1: 1-factor solution
ord_mod1 <- 'f =~ auto1 + auto2 + auto3 + auto4 + 
                  loc1 + loc2 + loc3 + loc4 + 
                  tol1 + tol2 + tol3 + tol4 + 
                  craving1 + craving2 + craving3 + craving4 +
                  taste1 + taste2 + taste3 +
                  cog_e1 + cog_e2 + cog_e3 +
                  w_control1 + w_control2 + w_control3 +
                  cue1 + cue2 + cue3 + 
                  affect1 + affect2 + affect3 + 
                  attach1 + attach2 + attach3 +
                  social1 + social2 +social3
                  '
ord_mod1_fit <- cfa(ord_mod1, 
                    data = data_cleaned, 
                    estimator = "WLSMV", 
                    ordered = items
                   )
summary(ord_mod1_fit, 
        standardized = TRUE, 
        fit.measures = TRUE
        )

#Model 2: 11-factor solution
ord_mod2 <- '#Primary dependence motives
             auto      =~ auto1 + auto2 + auto3 + auto4
             loc       =~ loc1 + loc2 + loc3 + loc4
             tol       =~ tol1 + tol2 + tol3 + tol4
             craving   =~ craving1 + craving2 + craving3 + craving4
             
             #Secondary dependence motives
             taste     =~ taste1 + taste2 + taste3
             cog_e     =~ cog_e1 + cog_e2 + cog_e3
             w_control =~ w_control1 + w_control2 + w_control3
             cue       =~ cue1 + cue2 + cue3
             affect    =~ affect1 + affect2 + affect3
             attach    =~ attach1 + attach2 + attach3
             social    =~ social1 + social2 +social3
             '
ord_mod2_fit <- cfa(ord_mod2, 
                    data = data_cleaned, 
                    estimator = "WLSMV", 
                    ordered = items
                    )
summary(ord_mod2_fit, 
        standardized = TRUE, 
        fit.measures = TRUE
        )

#Model 3: 2-factor solution
ord_mod3 <- 'pdm =~ auto1 + auto2 + auto3 + auto4 + 
                     loc1 + loc2 + loc3 + loc4 + 
                     tol1 + tol2 + tol3 + tol4 + 
                     craving1 + craving2 + craving3 + craving4
                     
              sdm =~ taste1 + taste2 + taste3 +
                     cog_e1 + cog_e2 + cog_e3 +
                     w_control1 + w_control2 + w_control3 +
                     cue1 + cue2 + cue3 + 
                     affect1 + affect2 + affect3 + 
                     attach1 + attach2 + attach3 +
                     social1 + social2 +social3
                     '
ord_mod3_fit <- cfa(ord_mod3, 
                    data = data_cleaned, 
                    estimator = "WLSMV", 
                    ordered = items
                   )
summary(ord_mod3_fit, 
        standardized = TRUE, 
        fit.measures = TRUE
        )

#Model 4: 2-order solution
ord_mod4 <- '#1st order
             auto      =~ auto1 + auto2 + auto3 + auto4
             loc       =~ loc1 + loc2 + loc3 + loc4
             tol       =~ tol1 + tol2 + tol3 + tol4
             craving   =~ craving1 + craving2 + craving3 + craving4
             taste     =~ taste1 + taste2 + taste3
             cog_e     =~ cog_e1 + cog_e2 + cog_e3
             w_control =~ w_control1 + w_control2 + w_control3
             cue       =~ cue1 + cue2 + cue3
             affect    =~ affect1 + affect2 + affect3
             attach    =~ attach1 + attach2 + attach3
             social    =~ social1 + social2 +social3
             
             #2nd order
             pdm =~ auto + loc + tol + craving
             sdm =~ taste + cog_e + w_control + cue + affect + attach + social
             '
ord_mod4_fit <- cfa(ord_mod4, 
                    data = data_cleaned, 
                    estimator = "WLSMV",
                    ordered = items
                    )
summary(ord_mod4_fit, 
        standardized = TRUE, 
        fit.measures = TRUE
        )

#Perform the chi-square DiffTest to assess the relative fitness:

#Relative fitness between the multidimensional solutions and the unidimensional solution
anova(ord_mod1_fit, ord_mod2_fit)
anova(ord_mod1_fit, ord_mod3_fit)
anova(ord_mod1_fit, ord_mod4_fit)
```

```{r, eval=FALSE}
#Select the most plausible continuous and ordinal WISDM-37 models
cont_select_fit <- 
ord_select_fit <- 

#Explore the modification indices of the selected WISMD-37 structural model 
wisdm_mi <- modificationIndices(...)

#Reconstruct the selected models following hypothesis-consistent modifications
cont_modified <- 
ord_modified <- 
```

```{r, eval=FALSE}
#Calculate composite reliability for the selected continuous and ordinal WISDM-37 model
cont_rel <- compRelSEM(...)
print(cont_rel, digits = 3)

ord_rel <- compRelSEM(...)
print(ord_rel, digits = 3)
```

```{r, eval=FALSE}
#Calculate the corrected item-total correlation for the selected WISDM-37 model

#Store items of each factors

```

```{r}
#Calculate the Fagerström Test for Nicotine Dependence scores for each method of smoking
data_cleaned$cigg_f = rowSums(data_cleaned[,82:87])
data_cleaned$ecigg_f = rowSums(data_cleaned[,88:93])
data_cleaned$h_f = rowSums(data_cleaned[,94:99])

#Calculate the mean score for each WISDM-37 factor
data_cleaned$auto = rowMeans(data_cleaned[,c(44, 53, 57, 68)])
data_cleaned$loc = rowMeans(data_cleaned[,c(45, 59, 64, 79)])
data_cleaned$tol = rowMeans(data_cleaned[,c(46, 72, 75, 80)])
data_cleaned$craving = rowMeans(data_cleaned[,c(47, 60, 66, 73)])
data_cleaned$taste = rowMeans(data_cleaned[,c(48, 58, 63)])
data_cleaned$cog_e = rowMeans(data_cleaned[,c(49, 56, 76)])
data_cleaned$w_control = rowMeans(data_cleaned[,c(50, 62, 78)])
data_cleaned$cue = rowMeans(data_cleaned[,c(51, 55, 67)])
data_cleaned$affect = rowMeans(data_cleaned[,c(52, 77, 81)])
data_cleaned$attach = rowMeans(data_cleaned[,c(54, 65, 69)])
data_cleaned$social = rowMeans(data_cleaned[,c(61, 70, 74)])
data_cleaned$pdm = rowMeans(data_cleaned[,105:108])
data_cleaned$sdm = rowMeans(data_cleaned[,109:115])


#Robust multiple linear regression analysis:

#WISDM-37 factors -> dependence on cigarettes
wisdm37_cigg <- lmrob(cigg_f ~ auto + loc + tol + craving + taste + cog_e + w_control + cue + affect + attach + social, 
                      data = data_cleaned,
                      k.max = 1000
                      )
cor.wisdm37.cigg <- (cor(data_cleaned[c(105:115, 102)], 
                         method = "spearman")^2
                     )*100
pcor.wisdm37.cigg <- (pcor(data_cleaned[c(105:115, 102)], 
                           method = "spearman")$estimate^2
                      )*100
summary(wisdm37_cigg)
print(cor.wisdm37.cigg)
print(pcor.wisdm37.cigg)

#WISDM-37 factors -> dependence on e-cigarettes
wisdm37_ecigg <- lmrob(ecigg_f ~ auto + loc + tol + craving + taste + cog_e + w_control + cue + affect + attach + social, 
                       data = data_cleaned,
                       k.max = 1000
                       )
cor.wisdm37.ecigg <- (cor(data_cleaned[c(105:115, 103)], 
                         method = "spearman")^2
                      )*100
pcor.wisdm37.ecigg <- (pcor(data_cleaned[c(105:115, 103)], 
                           method = "spearman")$estimate^2
                       )*100
summary(wisdm37_ecigg)
print(cor.wisdm37.ecigg)
print(pcor.wisdm37.ecigg)

#WISDM-37 factors -> dependence on hookah

wisdm37_h <- lmrob(h_f ~ auto + loc + tol + craving + taste + cog_e + w_control + cue + affect + attach + social,
                   data = data_cleaned,
                   k.max = 1000
                   )
cor.wisdm37.h <- (cor(data_cleaned[c(105:115, 104)], 
                         method = "spearman")^2
                 )*100
pcor.wisdm37.h <- (pcor(data_cleaned[c(105:115, 104)], 
                           method = "spearman")$estimate^2
                   )*100
summary(wisdm37_h)
print(cor.wisdm37.h)
print(pcor.wisdm37.h)
```

```{r}
#Confirmatory factor analysis for the RFQ:

#Based on continuous variables:

#Model 1: 1-factor solution
rfq_cmod1 <-'f =~ hc1 + hc2 + hc3 + hc4 + hc5 + sc1 + sc2 + sc3 + sc4 + sc5 +
                  ir1 + ir2 + ir3 + ir4 + ir5 + sp1 + sp2 + sp3 + sp4 + sp5
            '
rfq_cmod1_fit <- cfa(rfq_cmod1, 
                     data = data_cleaned, 
                     estimator = "MLR"
                     )
summary(rfq_cmod1_fit, 
        standardized = TRUE, 
        fit.measures = TRUE
        )

#Model 2: 4-factor solution
rfq_cmod2 <-'hc =~ hc1 + hc2 + hc3 + hc4 + hc5
             sc =~ sc1 + sc2 + sc3 + sc4 + sc5
             ir =~ ir1 + ir2 + ir3 + ir4 + ir5
             sp =~ sp1 + sp2 + sp3 + sp4 + sp5
             '
rfq_cmod2_fit <- cfa(rfq_cmod2, 
                     data = data_cleaned, 
                     estimator = "MLR"
                     )
summary(rfq_cmod2_fit, 
        standardized = TRUE, 
        fit.measures = TRUE
        )

#Model 3: 2-factor solution
rfq_cmod3 <-'intrinsic =~ hc1 + hc2 + hc3 + hc4 + hc5 + sc1 + sc2 + sc3 + sc4 + sc5
             extrinsic =~ ir1 + ir2 + ir3 + ir4 + ir5 + sp1 + sp2 + sp3 + sp4 + sp5
             '
rfq_cmod3_fit <- cfa(rfq_cmod3, 
                     data = data_cleaned, 
                     estimator = "MLR"
                     )
summary(rfq_cmod3_fit, 
        standardized = TRUE, 
        fit.measures = TRUE
        )

#Model 4: 2-order solution
rfq_cmod4 <-'#1st order
             hc =~ hc1 + hc2 + hc3 + hc4 + hc5
             sc =~ sc1 + sc2 + sc3 + sc4 + sc5
             ir =~ ir1 + ir2 + ir3 + ir4 + ir5
             sp =~ sp1 + sp2 + sp3 + sp4 + sp5
             
             #2nd order
             intrinsic =~ hc + sc
             extrinsic =~ ir + sp
             '
rfq_cmod4_fit <- cfa(rfq_cmod4, 
                     data = data_cleaned, 
                     estimator = "MLR"
                     )
summary(rfq_cmod4_fit, 
        standardized = TRUE, 
        fit.measures = TRUE
        )

#Based on ordinal variables:
rfq_items <- c("hc1", "hc2", "hc3", "hc4", "hc5",
               "sc1", "sc2", "sc3", "sc4", "sc5",
               "ir1", "ir2", "ir3", "ir4", "ir5",
               "sp1", "sp2", "sp3", "sp4", "sp5"
               )

#Model 1: 1-factor solution
rfq_omod1 <- 'f =~ hc1 + hc2 + hc3 + hc4 + hc5 + sc1 + sc2 + sc3 + sc4 + sc5 +
                   ir1 + ir2 + ir3 + ir4 + ir5 + sp1 + sp2 + sp3 + sp4 + sp5
              '
rfq_omod1_fit <- cfa(rfq_omod1, 
                     data = data_cleaned, 
                     estimator = "WLSMV", 
                     ordered = rfq_items
                     )
summary(rfq_omod1_fit, 
        standardized = TRUE, 
        fit.measures = TRUE
        )

#Model 2: 4-factor solution
rfq_omod2 <- 'hc =~ hc1 + hc2 + hc3 + hc4 + hc5
              sc =~ sc1 + sc2 + sc3 + sc4 + sc5
              ir =~ ir1 + ir2 + ir3 + ir4 + ir5
              sp =~ sp1 + sp2 + sp3 + sp4 + sp5
              '
rfq_omod2_fit <- cfa(rfq_omod2, 
                     data = data_cleaned, 
                     estimator = "WLSMV", 
                     ordered = rfq_items
                     )
summary(rfq_omod2_fit, 
        standardized = TRUE, 
        fit.measures = TRUE
        )

#Model 3: 2-factor solution
rfq_omod3 <- 'intrinsic =~ hc1 + hc2 + hc3 + hc4 + hc5 + sc1 + sc2 + sc3 + sc4 + sc5
              extrinsic =~ ir1 + ir2 + ir3 + ir4 + ir5 + sp1 + sp2 + sp3 + sp4 + sp5
              '
rfq_omod3_fit <- cfa(rfq_omod3, 
                     data = data_cleaned, 
                     estimator = "WLSMV", 
                     ordered = rfq_items
                     )
summary(rfq_omod3_fit, 
        standardized = TRUE, 
        fit.measures = TRUE
        )

#Model 4: 2-order solution
rfq_omod4 <- '#1st order
             hc =~ hc1 + hc2 + hc3 + hc4 + hc5
             sc =~ sc1 + sc2 + sc3 + sc4 + sc5
             ir =~ ir1 + ir2 + ir3 + ir4 + ir5
             sp =~ sp1 + sp2 + sp3 + sp4 + sp5
             
             #2nd order
             intrinsic =~ hc + sc
             extrinsic =~ ir + sp
             '
rfq_omod4_fit <- cfa(rfq_omod4, 
                     data = data_cleaned, 
                     estimator = "WLSMV", 
                     ordered = rfq_items
                     )
summary(rfq_omod4_fit, 
        standardized = TRUE, 
        fit.measures = TRUE
        )

#Relative fitness between the multidimensional solutions and the unidimensional solution
anova(rfq_omod1_fit, rfq_omod2_fit)
anova(rfq_omod1_fit, rfq_omod3_fit)
anova(rfq_omod1_fit, rfq_omod4_fit)
```

```{r, eval=FALSE}
#Select the most plausible continuous and ordinal RFQ models
rfq_cselect_fit <- 
rfq_oselect_fit <- 

#Explore the modification indices of the selected WISMD-37 structural model 
rfq_mi <- modificationIndices(...)

#Reconstruct the selected models following hypothesis-consistent modifications
rfq_cmodified <- 
rfq_omodified <- 
```

```{r, eval=FALSE}
#Calculate composite reliability for the selected continuous and ordinal RFQ model
rfq_cont_rel <- compRelSEM(...)
print(rfq_cont_rel, digits = 3)

rfq_ord_rel <- compRelSEM(...)
print(rfq_ord_rel, digits = 3)
```

```{r, eval=FALSE}
#Calculate the corrected item-total correlation for the selected RFQ model

#Store items of each factors

```

```{r}
#Calculate the RFQ scores
data_cleaned$hc = rowMeans(data_cleaned[,c(22, 26, 30, 34, 39)])
data_cleaned$sc = rowMeans(data_cleaned[,c(23, 27, 31, 36, 40)])
data_cleaned$ir = rowMeans(data_cleaned[,c(24, 28, 32, 37, 41)])
data_cleaned$sp = rowMeans(data_cleaned[,c(25, 29, 33, 38, 42)])
data_cleaned$intrinsic = rowMeans(data_cleaned[,c(118, 119)])
data_cleaned$extrinsic = rowMeans(data_cleaned[,c(120, 121)])

#Robust multiple linear regression analysis:

#RFQ factors -> dependence on cigarettes
rfq_time <- multinom(time_since_quitting ~ hc + sc + ir + sp, 
                     data = data_cleaned,
                     )
rfq_time_sum <- summary(rfq_time)

z_vals <- rfq_time_sum$coefficients / rfq_time_sum$standard.errors
p_vals <- 2 * (1 - pnorm(abs(z_vals)))

rfq_time_sum
p_vals
```
